// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.chen.spring.rest.model;

import com.chen.spring.rest.model.ClickEventDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ClickEventDataOnDemand_Roo_Configurable {
    
    declare @type: ClickEventDataOnDemand: @Configurable;
    
}
