// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.chen.spring.rest.model;

import com.chen.spring.rest.model.ClickEvent;
import com.chen.spring.rest.model.ClickEventDataOnDemand;
import com.chen.spring.rest.model.ClickEventIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ClickEventIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ClickEventIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ClickEventIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ClickEventIntegrationTest: @Transactional;
    
    @Autowired
    ClickEventDataOnDemand ClickEventIntegrationTest.dod;
    
    @Test
    public void ClickEventIntegrationTest.testCountClickEvents() {
        Assert.assertNotNull("Data on demand for 'ClickEvent' failed to initialize correctly", dod.getRandomClickEvent());
        long count = ClickEvent.countClickEvents();
        Assert.assertTrue("Counter for 'ClickEvent' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ClickEventIntegrationTest.testFindClickEvent() {
        ClickEvent obj = dod.getRandomClickEvent();
        Assert.assertNotNull("Data on demand for 'ClickEvent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ClickEvent' failed to provide an identifier", id);
        obj = ClickEvent.findClickEvent(id);
        Assert.assertNotNull("Find method for 'ClickEvent' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ClickEvent' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ClickEventIntegrationTest.testFindAllClickEvents() {
        Assert.assertNotNull("Data on demand for 'ClickEvent' failed to initialize correctly", dod.getRandomClickEvent());
        long count = ClickEvent.countClickEvents();
        Assert.assertTrue("Too expensive to perform a find all test for 'ClickEvent', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ClickEvent> result = ClickEvent.findAllClickEvents();
        Assert.assertNotNull("Find all method for 'ClickEvent' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ClickEvent' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ClickEventIntegrationTest.testFindClickEventEntries() {
        Assert.assertNotNull("Data on demand for 'ClickEvent' failed to initialize correctly", dod.getRandomClickEvent());
        long count = ClickEvent.countClickEvents();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ClickEvent> result = ClickEvent.findClickEventEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ClickEvent' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ClickEvent' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ClickEventIntegrationTest.testFlush() {
        ClickEvent obj = dod.getRandomClickEvent();
        Assert.assertNotNull("Data on demand for 'ClickEvent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ClickEvent' failed to provide an identifier", id);
        obj = ClickEvent.findClickEvent(id);
        Assert.assertNotNull("Find method for 'ClickEvent' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyClickEvent(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ClickEvent' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ClickEventIntegrationTest.testMergeUpdate() {
        ClickEvent obj = dod.getRandomClickEvent();
        Assert.assertNotNull("Data on demand for 'ClickEvent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ClickEvent' failed to provide an identifier", id);
        obj = ClickEvent.findClickEvent(id);
        boolean modified =  dod.modifyClickEvent(obj);
        Integer currentVersion = obj.getVersion();
        ClickEvent merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ClickEvent' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ClickEventIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ClickEvent' failed to initialize correctly", dod.getRandomClickEvent());
        ClickEvent obj = dod.getNewTransientClickEvent(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ClickEvent' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ClickEvent' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ClickEvent' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ClickEventIntegrationTest.testRemove() {
        ClickEvent obj = dod.getRandomClickEvent();
        Assert.assertNotNull("Data on demand for 'ClickEvent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ClickEvent' failed to provide an identifier", id);
        obj = ClickEvent.findClickEvent(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ClickEvent' with identifier '" + id + "'", ClickEvent.findClickEvent(id));
    }
    
}
